Setting hashed user password during isntall.

diff --git a/curios-install b/curios-install
--- a/curios-install
+++ b/curios-install
@@ -4,10 +4,10 @@
 # Meant to be run during an NixOS ISO installation.
 # !IMPORTANT! Run this script as sudo
 # It will create 3 partitions for '/boot', '/' and a 8Go swap
-# OR with --crypt option, it will create a 512Mo boot and a LUKS partition.
-# The encrypted LUKS partition will contain LVM partitions for '/' and a 8Go swap.
+# If disk encryption is choosed, the encrypted LUKS partition will contain LVM
+# partitions for '/' and a 8Go swap.
 #
-# Dependencies: dialog, parted, git.
+# Dependencies: dialog, parted, git, mkpasswd.
 # Test it with:
 # nix-shell -p dialog parted git
 
@@ -35,6 +35,7 @@ SELECTED_LOCALE_CONSOLE="us"
 SELECTED_TZ=""
 USERNAME="nixos"
 FULLNAME=""
+HASHED_USER_PASSWD=""
 ENCRYPT_DISK=0
 DISK_LUKS_KEY=""
 GPU_VENDOR_DETECTED=""
@@ -169,6 +170,10 @@ if ! available mkfs; then
   echo -e "${RED}mkfs command not found!${NC}"
   exit 2
 fi
+if ! available mkpasswd; then
+  echo -e "${RED}mkpasswd command not found!${NC}"
+  exit 2
+fi
 if ! available dialog; then
   echo -e "${RED}dialog command not found!${NC}"
   exit 2
@@ -182,11 +187,14 @@ else
   exit 1
 fi
 
+#------------- Settings and checks
 # This script must be run as root
 if [ "$EUID" -ne 0 ]; then
   echo -e "${RED}This script MUST be run as root:${NC} sudo curios-install" >&2
   exit 1
 fi
+
+setterm -blink on
 
 # A standard dialog message box, for printing error message
 display_error() {
@@ -548,7 +556,8 @@ set_fullname() {
       display_error "\Zb\Z1Invalid full name!\Zn it could only contain alphanumerical, '.' or space characters."
       set_fullname
     else
-      display_password_info
+      #display_password_info
+      set_user_passwd
     fi
     ;;
   "$DIALOG_CANCEL")
@@ -590,6 +599,53 @@ display_password_info() {
     exit 1
     ;;
   esac
+}
+
+#------------- Set user password
+set_user_passwd() {
+  exec 3>&1
+  result=$(dialog --backtitle "User Password -- $DIALOG_HELP_TITLE" \
+    --title "User Password" \
+    --cancel-label "Previous" \
+    --ok-label "Next" \
+    --no-collapse \
+    --clear \
+    --colors \
+    --insecure \
+    --passwordform "Please enter and confirm your password." 0 0 0 \
+    "Password:" 1 1 "" 1 10 25 30 \
+    "Confirm:" 2 1 "" 2 10 25 30 \
+    2>&1 1>&3)
+  exit_status=$?
+  exec 3>&-
+  case $exit_status in
+  "$DIALOG_OK")
+    clear
+    password=$(echo "$result" | head -n 1)
+    confirm=$(echo "$result" | tail -n 1)
+    # Compare and check password length
+    if [ "${#password}" -le 5 ]; then
+      display_error "\Zb\Z1Password is too short!\Zn It should be at least 6 characters long."
+      set_user_passwd
+    elif [[ "$password" != "$confirm" ]]; then
+      display_error "\Zb\Z1Password mismatch!\Zn Password and confirmation are different."
+      set_user_passwd
+    else
+      HASHED_USER_PASSWD=$(mkpasswd -m yescrypt "$password")
+      choose_disk
+    fi
+    ;;
+  "$DIALOG_CANCEL")
+    clear
+    set_fullname
+    ;;
+  "$DIALOG_ESC")
+    clear
+    echo "Program aborted." >&2
+    exit 1
+    ;;
+  esac
+
 }
 
 #------------- Choose install disk
@@ -634,7 +690,7 @@ choose_disk() {
     ;;
   "$DIALOG_CANCEL")
     clear
-    set_fullname
+    set_user_passwd
     ;;
   "$DIALOG_ESC")
     clear
@@ -814,6 +870,7 @@ if [ $VERBOSE -eq 1 ]; then
   echo "time zone: $SELECTED_TZ"
   echo "hostname: $PC_HOSTNAME"
   echo "username: $USERNAME"
+  echo "user hashed password: $HASHED_USER_PASSWD"
   echo "user full name: $FULLNAME"
   echo "install on disk: $SELECTED_DISK"
   echo "encrypt disk: $ENCRYPT_DISK"
@@ -975,9 +1032,10 @@ if [ $CONFIRM_INSTALL -eq 1 ]; then
   sed "s/keyboard = \".*/keyboard = \"${SELECTED_LOCALE_CONSOLE}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
   # Update time zone
   sed "s/timeZone = \".*/timeZone = \"${SELECTED_TZ//\//\\\/}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
-  # Update user name
+  # User settings
   sed "s/users\..*/users.${USERNAME} = {/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
   sed "s/description = \".*/description = \"${FULLNAME}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
+  sed "s/initialHashedPassword = \".*/initialHashedPassword = \"${HASHED_USER_PASSWD}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
   # Update hostname
   sed "s/hostname = \".*/hostname = \"${PC_HOSTNAME}\";/g" -i "$NIXOS_CONFIG_DIR"/settings.nix
   # platform settings:
