Curios Manager: added firmware update with fwupdmgr.

diff --git a/pkgs/curios-manager/bin/curios-manager b/pkgs/curios-manager/bin/curios-manager
--- a/pkgs/curios-manager/bin/curios-manager
+++ b/pkgs/curios-manager/bin/curios-manager
@@ -25,7 +25,7 @@ LIST_GEN_DATE="";
 LIST_GEN_KERNEL="";
 
 export GUM_CHOOSE_CURSOR_FOREGROUND="#26a269"
-#export GUM_CONFIRM_SELECTED_FOREGROUND="#d0cfcc"
+export GUM_CHOOSE_SELECTED_FOREGROUND="#26a269"
 export GUM_CONFIRM_SELECTED_BACKGROUND="#26a269"
 
 #------------- Print help function
@@ -103,6 +103,10 @@ if ! available gum; then
 fi
 if ! available tte; then
   echo -e "${RED}tte command not found!${NC}"
+  exit 2
+fi
+if ! available fwupdmgr; then
+  echo -e "${RED}fwupdmgr command not found!${NC}"
   exit 2
 fi
 # Get current OS version
@@ -188,7 +192,7 @@ system_menu() {
   local SETTINGS_FILE
   local SETTINGS_LAST_MOD
   local SYSTEM_MENU
-  SYSTEM_MENU=$(gum choose " Shutdown" " Reboot" " Lock session" "󱃶 Process Management" "󰋊 Disk usage" " Settings (manual edit)" " Info" " Back" )
+  SYSTEM_MENU=$(gum choose " Shutdown" " Reboot" " Lock session" "󱃶 Process Management" "󰋊 Disk usage" " Settings (manual edit)" " Firmware" " Info" " Back" )
   case $SYSTEM_MENU in
     " Shutdown")
       #sudo shutdown -P now
@@ -221,6 +225,25 @@ system_menu() {
         nix_generations
         echo -e "Latest update: ${LIST_GEN_DATE} - Kernel: ${LIST_GEN_KERNEL}"
         reboot_check
+      fi
+      ;;
+    " Firmware")
+      gum spin --spinner globe --title "Refreshing firmware metadata..." --show-error -- fwupdmgr refresh --force
+      DEVICES_UPDATE=$(fwupdmgr --json get-updates)
+      if [[ $(echo "$DEVICES_UPDATE" | jq -r '.Devices | length') -ge 1 ]]; then
+        echo -e "The following devices can be upgraded:"
+        echo ""
+        echo "$DEVICES_UPDATE" | jq -c '.Devices.[]' | while read -r item; do
+          DeviceName=$(echo "$item" | jq -r '.Name')
+          DeviceSummary=$(echo "$item" | jq -r '.Summary')
+          DeviceVendor=$(echo "$item" | jq -r '.Vendor')
+          #DeviceID=$(echo "$item" | jq -r '.DeviceId')
+          echo -e "- ${GREEN}$DeviceName${NC} (${BLUE}$DeviceVendor${NC}) [$DeviceSummary]"
+        done
+        echo ""
+        gum confirm "Would you like to update all devices now ?" && sudo whoami 1>/dev/null && gum spin --spinner dot --title "Updating firmware..." --show-error -- sudo fwupdmgr update
+      else
+        echo -e "${GREEN}Nothing to update.${NC}"
       fi
       ;;
     " Info")
